### ISSUE TITLE
plotCHOIR split.by option

### ISSUE THREAD

**Issue by Carolina-Toste** [corceslab/CHOIR#9]
Hi there,

Thank you so much for this package, it's really great . I've been testing it on my data and I have successfully plotted the CHOIR clusters umap plot. I wanted to try to plot these clusters split.by genotype, but that functionality seems not to be supported(unless I'm somehow made a mistake).  Could you let me know if by any chance this will change in the future? I did manage to get the plot I wanted with
`````
DimPlot(seurat, pt.size=2, split.by ="Genotype", group.by = "CHOIR_clusters_0.05", reduction ="CHOIR_P0_reduction_UMAP")
`````

**Comment by catpetersen** [comment]
Hi! Glad you like the package! 

This is a good catch—I've made some changes to `plotCHOIR()` to accommodate more of the `Seurat::DimPlot` parameters like `split.by` in a new branch: 'dev_seurat_compatibility'. 

Would you try reinstalling CHOIR with this branch, and let me know if `split.by` works for you?

```
remotes::install_github("corceslab/CHOIR", ref = "dev_seurat_compatibility", repos = BiocManager::repositories(), upgrade = "never")
# To unload a package and reload
detach("package:CHOIR", unload = TRUE)
library(CHOIR)
```

**Comment by catpetersen** [comment]
Hi! I'm closing this issue for now, but please feel free to reply here if you have any additional issues and I'll reopen it.
